### ISSUE TITLE
Multi-line secrets don't work

### ISSUE THREAD

**Issue by ikke-t** [hybrid-cloud-patterns/multicloud-gitops#62]
I tried to push secret to vault, and run into problem secrets are read line by line, not as yaml key: value.

Example:
```yaml
secrets:
  ldap:
    bindPassword: xxx
    bindDN: xxx
    url: xxx
    groupsBaseDN: xxx
    usersBaseDN: xxx
    ca_crt: |
      -----BEGIN CERTIFICATE-----
      MIIEgjCCAuqgAwIBAgIBATANBgkqhkiG9w0BAQsFADAzMREwDwYDVQQKDAhDT09M
      LkxBQjEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTIyMDEwNTEz
      ...
```

Error:

```yaml
"rc": 127, "return_code": 127, "stderr": "Failed to parse K=V data: invalid key/value pair \"CERTIFICATE-----\": format must be key=value\nsh: line 1: MIIEgjCCAuqgAwIBAgIBATANBgkqhkiG9w0BAQsFADAzMREwDwYDVQQKDAhDT09M: command not found\nsh: line 2: LkxBQjEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTIyMDEwNTEz: command not found\nsh: line 3: MjA1MloXDTQyMDEwNTEzMjA1MlowMzERMA8GA1UECgwIQ09PTC5MQUIxHjAcBgNV: command not found\nsh: line 4: BAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTCCAaIwDQYJKoZIhvcNAQEBBQADggGP: command not found\nsh: line 5: ADCCAYoCggGBANhvBhWj5qQWpvO6h6yDvCKhc/Nj36xZN1990L2PGL6dJU2SoOuo: No such file or directory\n
```
